In [2]:
import numpy as np

In [18]:
arr0=np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
arr=np.arange(10,49)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [23]:
arr.shape

(39,)

In [25]:
arr.dtype

dtype('int32')

In [28]:
print(np.__version__)
print()
print(np.show_config())

1.19.4

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [30]:
print(arr.ndim)

1


In [36]:
bool_arr=np.array([1,'2a','A',32.65,True,'%',6700],dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True]


In [40]:
arr2=np.arange(28).reshape(7,4)
arr2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [42]:
arr3=np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
np.flip(arr)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [49]:
arr0=np.zeros(10)
print(arr0)
arr0[5]=1
arr0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [53]:
i=np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr.astype(float)

int32


array([1., 2., 3., 4., 5.])

In [59]:
r1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

r2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(r1,r2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [64]:
r1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

r2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comp=(r1==r2)
comp

array([[False, False, False],
       [False, False, False]])

In [77]:
arr1=np.arange(10)
odd=arr1%2==1
arr1[odd]

array([1, 3, 5, 7, 9])

In [78]:
arr1[odd]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [80]:
arr = np.arange(10)
np.put(arr,[5,6,7,8],12)
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [87]:
arr1=np.ones((5,5))
print(arr1)
arr1[1:-1,1:-1]=0
arr1

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [91]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr2=np.arange(10).reshape(2,5)
print(arr2)
print()
print(arr2[0])


[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4]


In [99]:
arr2=np.arange(10).reshape(2,5)
print(arr2)
arr2[1,1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

In [100]:
arr2=np.arange(10).reshape(2,5)
print(arr2)
arr2[0:2,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

In [107]:
ran=np.random.randint(1000,size=(10,10))
print(ran)
print(np.amin(ran))
print(np.amax(ran))

[[759 221 465 575 234 339 741 715 132 611]
 [706 326 992 852 217 754 935 966 943 288]
 [318 126 196 447 765 403 252 820 421 259]
 [922 186 845 857 361 578 511 350 583 174]
 [203 189 419 705 422 220 523 232 428 744]
 [148 236 221 526 524 436 905 548 833 306]
 [589 903 783 861 124 367 968 618 934 614]
 [166 585 572 489 976 798 916 139  21 161]
 [919 346 542 286 161 982 449 164  29 894]
 [677 372 889 886   6 229 115 216 204 631]]
6
992


In [109]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
com=np.intersect1d(a,b)
com

array([2, 4])

In [115]:
a==b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

In [120]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[names!='Will']

[[ 0.93797473 -1.21460145 -1.28025415 -0.86512935]
 [ 0.04700308  0.4769843   1.81403652 -0.04158276]
 [ 1.14816477 -0.80380056 -0.41807138 -0.31416124]
 [-0.40207627 -1.00820033 -0.90123386 -0.71539533]
 [-0.74277437  1.6679619  -0.34362367 -1.07844265]
 [-0.81792102  3.60565843 -0.06996205 -0.96909965]
 [ 0.35676687  0.83837713  0.05770605 -0.08690701]]


array([[ 0.93797473, -1.21460145, -1.28025415, -0.86512935],
       [ 0.04700308,  0.4769843 ,  1.81403652, -0.04158276],
       [-0.40207627, -1.00820033, -0.90123386, -0.71539533],
       [-0.81792102,  3.60565843, -0.06996205, -0.96909965],
       [ 0.35676687,  0.83837713,  0.05770605, -0.08690701]])

In [121]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[(names!='Will')&(names!='Joe')]

[[ 1.01611731e+00  1.63502906e+00 -2.10564317e+00 -1.65458621e-01]
 [ 1.71064890e+00 -3.51261595e-01  1.64683967e+00 -2.27707065e-01]
 [ 5.95953930e-01 -1.88532425e+00  3.22308354e-01 -1.07208311e+00]
 [ 5.85361463e-01  1.39023536e+00 -5.88697827e-02  1.82757414e-01]
 [ 4.26057963e-01  4.48092889e-01  7.75785587e-01 -2.36938339e+00]
 [-1.95810096e-01  2.42805422e-01 -1.87973522e+00 -3.64004232e-01]
 [ 1.29319101e-03  1.54798383e+00 -2.74911135e-01  9.24915933e-03]]


array([[ 1.01611731,  1.63502906, -2.10564317, -0.16545862],
       [ 0.58536146,  1.39023536, -0.05886978,  0.18275741]])

In [124]:
arr = np.random.uniform(1,15, size=(5,3))
print(arr)

[[11.25575706 10.61916176  7.8366676 ]
 [14.18715038 13.76964502 10.94482637]
 [ 9.50987441  5.64198542  5.94351137]
 [ 4.7631402  10.98554897  6.02648898]
 [13.16108489  1.98804005 10.43251661]]


In [126]:
rand = np.random.uniform(1,16, size=(2,2,4))
print(rand)

[[[11.09619401  1.42448679  7.54033171  4.14647131]
  [15.46235449  7.46505983  7.79793122 11.14095883]]

 [[13.3162534   6.95155246  8.2508958  10.38194913]
  [ 4.49913929  2.78338022  3.45599868 12.59691036]]]


In [130]:
np.swapaxes(rand,1,0)

array([[[11.09619401,  1.42448679,  7.54033171,  4.14647131],
        [13.3162534 ,  6.95155246,  8.2508958 , 10.38194913]],

       [[15.46235449,  7.46505983,  7.79793122, 11.14095883],
        [ 4.49913929,  2.78338022,  3.45599868, 12.59691036]]])

In [153]:
ran=np.random.normal(10,size=(2,5))
print(ran)
sqr=np.sqrt(ran)
print(sqr)

[[ 7.64128949  9.19753418 10.64172481 10.37351675  9.33188599]
 [10.27311029  9.50216698 11.03909046 10.31032833 11.0006255 ]]
[[2.76428824 3.03274367 3.26216566 3.22079443 3.05481358]
 [3.20516931 3.08255851 3.32251267 3.21097    3.31671909]]


In [158]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
r=np.setdiff1d(a,b)
r

array([1, 2, 3, 4])

In [154]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)


array([[ 28.,  64.],
       [ 67., 181.]])

In [155]:
ran=np.random.normal(20,size=(4,5))
print(ran)
ran.cumsum()

[[18.97393319 21.70718272 20.77870559 20.44014889 21.19117265]
 [22.41015914 18.45616511 21.43606306 20.00938772 18.29555808]
 [20.78424823 19.50602882 20.23927373 18.8879248  20.7706792 ]
 [19.43435987 21.15460792 20.63883925 20.64499679 21.14182855]]


array([ 18.97393319,  40.68111591,  61.4598215 ,  81.89997039,
       103.09114304, 125.50130218, 143.95746728, 165.39353035,
       185.40291807, 203.69847614, 224.48272437, 243.98875319,
       264.22802692, 283.11595172, 303.88663092, 323.32099079,
       344.47559871, 365.11443796, 385.75943475, 406.9012633 ])

In [160]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
n=np.unique(names)
n

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [165]:
sample= np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sample)
new = np.array([[10,10,10]])
sample[:,1]=new
sample

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [169]:
ar1=np.random.normal(12,size=(4,3))
print(ar1)
print()
ar2=np.random.normal(12,size=(4,3))
print(ar2)
r=np.maximum(ar1,ar2)
r

[[11.00449047 12.25050262 11.81773672]
 [14.25616751 11.0871052  13.93325563]
 [14.06863507 12.19180818 11.96439094]
 [10.97025092 13.80518549 11.4726563 ]]

[[11.0010628  10.9664085  12.04429152]
 [12.11022394 11.35660237 11.93964553]
 [13.40458518 11.35463327 13.40771732]
 [12.28363021 12.13799401 11.36966694]]


array([[11.00449047, 12.25050262, 12.04429152],
       [14.25616751, 11.35660237, 13.93325563],
       [14.06863507, 12.19180818, 13.40771732],
       [12.28363021, 13.80518549, 11.4726563 ]])